version: "3.4"
services:
    mps_daemon:
        container_name: mps-daemon
        runtime: nvidia
        image: nvidia/cuda:12.3.1-base-ubuntu20.04
        ipc: shareable
        environment:
          - NVIDIA_VISIBLE_DEVICES=0
        command: tail -f /dev/null
        volumes: 
          - mps_0:/tmp/mps_0
          - mps_log_0:/tmp/mps_log_0

    mps_client:
        depends_on:
          - mps_daemon
        runtime: nvidia
        image: nvidia/cuda:12.3.1-base-ubuntu20.04
        ipc: container:mps-daemon
        environment:
          - NVIDIA_VISIBLE_DEVICES=0
        command: tail -f /dev/null
        volumes:
          - mps_0:/tmp/mps_0
          - mps_log_0:/tmp/mps_log_0
volumes:
    mps_0:
    mps_log_0:
