version: "3.4"
services:
    mps_daemon:
        container_name: mps-daemon
        # runtime: nvidia
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        image: nvidia/cuda:12.3.1-base-ubuntu20.04
        ipc: shareable
        environment:
          - CUDA_VISIBLE_DEVICES=0
          - CUDA_MPS_PIPE_DIRECTORY=/tmp/mps_0
          - CUDA_MPS_LOG_DIRECTORY=/tmp/mps_log_0
        command: tail -f /dev/null
        volumes: 
          - mps_0:/tmp/mps_0
          - mps_log_0:/tmp/mps_log_0

    mps_client:
        depends_on:
          - mps_daemon
        #runtime: nvidia
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        image: nvidia/cuda:12.3.1-base-ubuntu20.04
        ipc: container:mps-daemon
        environment:
          - CUDA_VISIBLE_DEVICES=0
          - CUDA_MPS_PIPE_DIRECTORY=/tmp/mps_0
          - CUDA_MPS_LOG_DIRECTORY=/tmp/mps_log_0
        command: tail -f /dev/null
        volumes:
          - mps_0:/tmp/mps_0
          - mps_log_0:/tmp/mps_log_0
volumes:
    mps_0:
        driver_opts:
            type: tmpfs
            device: tmpfs
    mps_log_0:
        driver_opts:
            type: tmpfs
            device: tmpfs
