version: '3'
services:
  web:
    image: nginx
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 500M
        reservations:
          cpus: '0.50'
          memory: 50M
