########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

version: '3'

networks:
SKELETON_SUBNETS
volumes:
  fate_flow_logs:
  shared_dir_examples:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/host/dir/examples
  shared_dir_federatedml:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/host/dir/federatedml

services:
  federation:
    build: FEDERATION_BUILD_FOLDER
    image: "${PREFIX}/federation:${TAG}-PARTY_ID"
    expose:
      - 9394
    volumes:
      - ./confs/federation/conf:/data/projects/fate/federation/conf
    networks:
        FEDERATION_NETWORK:
            ipv4_address: PRE-ASSIGNED_FEDERATION_IP
    cap_add:
      - NET_ADMIN

  proxy:
    build: PROXY_BUILD_FOLDER
    image: "${PREFIX}/proxy:${TAG}-PARTY_ID"
    expose:
      - 9370
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    volumes:
      - ./confs/proxy/conf:/data/projects/fate/proxy/conf
    networks:
        PROXY_NETWORK:
            ipv4_address: PRE-ASSIGNED_PROXY_IP
    cap_add:
      - NET_ADMIN

  fateboard:
    build: FATEBOARD_BUILD_FOLDER
    image: "${PREFIX}/fateboard:${TAG}-PARTY_ID"
    ports:
      - "FATEBOARD_HOST_PORT:8080"
    volumes:
      - ./confs/fateboard/conf:/data/projects/fate/fateboard/conf
      - fate_flow_logs:/data/projects/fate/python/logs
    networks:
        FATEBOARD_NETWORK:
            ipv4_address: PRE-ASSIGNED_FATEBOARD_IP
    cap_add:
      - NET_ADMIN
    depends_on:
      - meta-service
      - python

  roll:
    build: ROLL_BUILD_FOLDER
    image: "${PREFIX}/roll:${TAG}-PARTY_ID"
    expose:
      - 8011
    volumes:
      - ./confs/roll/conf:/data/projects/fate/roll/conf
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    networks:
        ROLL_NETWORK:
            ipv4_address: PRE-ASSIGNED_ROLL_IP
    cap_add:
      - NET_ADMIN
    depends_on:
      - meta-service

  egg:
    build: EGG_BUILD_FOLDER
    image: "${PREFIX}/egg:${TAG}-PARTY_ID"
    expose:
      - 7888
      - 7778
      - "50000-60000"
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: cpp 
      LD_LIBRARY_PATH: $$LD_LIBRARY_PATH:/usr/local/lib:/data/projects/fate/eggroll/storage-service-cxx/third_party/lib
      PYTHONPATH: /data/projects/fate/eggroll/python
      GLOG_log_dir: /data/projects/fate/eggroll/storage-service-cxx/logs
    volumes:
        - ./confs/egg/conf:/data/projects/fate/eggroll/egg/conf
        - ./confs/federatedml/conf/server_conf.json:/data/projects/fate/eggroll/python/eggroll/conf/server_conf.json
        - ./confs/egg/data-dir:/data/projects/fate/data-dir
    networks:
        EGG_NETWORK:
            ipv4_address: PRE-ASSIGNED_EGG_IP
    cap_add:
      - NET_ADMIN

  python:
    build: PYTHON_BUILD_FOLDER
    image: "${PREFIX}/python:${TAG}-PARTY_ID"
    expose:
      - 9360
      - 9380
    restart: always
    volumes:
      - shared_dir_federatedml:/data/projects/fate/python/federatedml
      - shared_dir_examples:/data/projects/fate/python/examples
      - ./confs/federatedml/conf:/data/projects/fate/python/arch/conf
      - ./confs/federatedml/conf:/data/projects/fate/python/eggroll/conf
      - ./confs/fate_flow/conf/settings.py:/data/projects/fate/python/fate_flow/settings.py
      - ./confs/fate_flow/conf/server_conf.json:/data/projects/fate/python/arch/conf/server_conf.json
      - fate_flow_logs:/data/projects/fate/python/logs
    depends_on:
      - redis
      - meta-service
      - proxy
      - roll
      - egg
      - mysql
    networks:
        PYTHON_NETWORK:
            ipv4_address: PRE-ASSIGNED_PYTHON_IP
    cap_add:
      - NET_ADMIN

  meta-service:
    build: META-SERVICE_BUILD_FOLDER
    image: "${PREFIX}/meta-service:${TAG}-PARTY_ID"
    expose:
      - 8590
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    volumes:
      - ./confs/meta-service/conf:/data/projects/fate/meta-service/conf
    depends_on:
      - mysql
    networks:
        META-SERVICE_NETWORK:
            ipv4_address: PRE-ASSIGNED_META-SERVICE_IP
    cap_add:
      - NET_ADMIN

  mysql:
    build: MYSQL_BUILD_FOLDER
    image: "mysql:8-PARTY_ID"
    expose:
      - 3306
    volumes:
      - ./confs/mysql/init:/docker-entrypoint-initdb.d/
      - ./confs/mysql/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fate_dev
      MYSQL_DATABASE: fate
      MYSQL_USER: fate
      MYSQL_PASSWORD: fate_dev
    networks:
        MYSQL_NETWORK:
            ipv4_address: PRE-ASSIGNED_MYSQL_IP
    cap_add:
      - NET_ADMIN


  redis:
    build: REDIS_BUILD_FOLDER
    image: "redis:5-PARTY_ID"
    expose:
      - 6379
    # command: redis-server --requirepass fate_dev
    volumes:
      - ./confs/redis/data:/data
    networks:
        REDIS_NETWORK:
            ipv4_address: PRE-ASSIGNED_REDIS_IP
    cap_add:
      - NET_ADMIN

