#!/bin/bash
cat /tmp/etc-hosts >> /etc/hosts
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.152.0.254 dev net0
source /opt/conda/etc/profile.d/conda.sh && conda activate py310 && export LD_LIBRARY_PATH=$HOME/miniconda3/envs/fedprox/lib/python3.10/site-packages/nvidia/nvjitlink/lib:$LD_LIBRARY_PATH && flower-superlink --insecure &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

